# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-01 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 10, 32, 57, 486980, tzinfo=utc)),
        ),
    ]
