# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-01 11:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190401_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 11, 2, 5, 576375, tzinfo=utc)),
        ),
    ]
