# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-01 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190401_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 14, 12, 26, 571626, tzinfo=utc)),
        ),
    ]
